AltunkayaBurada/AltunkayaBurada/Controllers/AltunsatablesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AltunkayaBurada.Models;

namespace AltunkayaBurada.Controllers
{
    public class AltunsatablesController : Controller
    {
        private readonly AltunkayadbContext _context;

        public AltunsatablesController(AltunkayadbContext context)
        {
            _context = context;
        }

       
        public async Task<IActionResult> Index()
        {
              return _context.Altunsatables != null ? 
                          View(await _context.Altunsatables.ToListAsync()) :
                          Problem("Entity set 'AltunkayadbContext.Altunsatables'  is null.");
        }

       
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Altunsatables == null)
            {
                return NotFound();
            }

            var altunsatable = await _context.Altunsatables
                .FirstOrDefaultAsync(m => m.Id == id);
            if (altunsatable == null)
            {
                return NotFound();
            }

            return View(altunsatable);
        }

       
        public IActionResult Create()
        {
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UrunAdi,EklenmeTarihi,SontuketimTarihi")] Altunsatable altunsatable)
        {
            if (ModelState.IsValid)
            {
                _context.Add(altunsatable);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(altunsatable);
        }

        
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Altunsatables == null)
            {
                return NotFound();
            }

            var altunsatable = await _context.Altunsatables.FindAsync(id);
            if (altunsatable == null)
            {
                return NotFound();
            }
            return View(altunsatable);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UrunAdi,EklenmeTarihi,SontuketimTarihi")] Altunsatable altunsatable)
        {
            if (id != altunsatable.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(altunsatable);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AltunsatableExists(altunsatable.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(altunsatable);
        }

      
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Altunsatables == null)
            {
                return NotFound();
            }

            var altunsatable = await _context.Altunsatables
                .FirstOrDefaultAsync(m => m.Id == id);
            if (altunsatable == null)
            {
                return NotFound();
            }

            return View(altunsatable);
        }

        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Altunsatables == null)
            {
                return Problem("Entity set 'AltunkayadbContext.Altunsatables'  is null.");
            }
            var altunsatable = await _context.Altunsatables.FindAsync(id);
            if (altunsatable != null)
            {
                _context.Altunsatables.Remove(altunsatable);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AltunsatableExists(int id)
        {
          return (_context.Altunsatables?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

AltunkayaBurada/AltunkayaBurada/Controllers/ConfytablesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AltunkayaBurada.Models;
using Microsoft.Identity.Client;

namespace AltunkayaBurada.Controllers
{
    public class ConfytablesController : Controller
    {
        private readonly AltunkayadbContext _context;

        public ConfytablesController(AltunkayadbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return _context.Confytables != null ?
                        View(await _context.Confytables.ToListAsync()) :
                        Problem("Entity set 'AltunkayadbContext.Confytables'  is null.");
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Confytables == null)
            {
                return NotFound();
            }

            var confytable = await _context.Confytables
                .FirstOrDefaultAsync(m => m.Id == id);
            if (confytable == null)
            {
                return NotFound();
            }

            return View(confytable);
        }
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UrunAdi,EklenmeTarihi,SontuketimTarihi")] Confytable confytable)
        {
            if (ModelState.IsValid)
            {
                _context.Add(confytable);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(confytable);
        }


        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Confytables == null)
            {
                return NotFound();
            }

            var confytable = await _context.Confytables.FindAsync(id);
            if (confytable == null)
            {
                return NotFound();
            }
            return View(confytable);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UrunAdi,EklenmeTarihi,SontuketimTarihi")] Confytable confytable)
        {
            if (id != confytable.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(confytable);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ConfytableExists(confytable.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(confytable);
        }


        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Confytables == null)
            {
                return NotFound();
            }

            var confytable = await _context.Confytables
                .FirstOrDefaultAsync(m => m.Id == id);
            if (confytable == null)
            {
                return NotFound();
            }

            return View(confytable);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Confytables == null)
            {
                return Problem("Entity set 'AltunkayadbContext.Confytables'  is null.");
            }
            var confytable = await _context.Confytables.FindAsync(id);
            if (confytable != null)
            {
                _context.Confytables.Remove(confytable);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ConfytableExists(int id)
        {
            return (_context.Confytables?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

AltunkayaBurada/AltunkayaBurada/Controllers/MahmoodtablesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AltunkayaBurada.Models;

namespace AltunkayaBurada.Controllers
{
    public class MahmoodtablesController : Controller
    {
        private readonly AltunkayadbContext _context;

        public MahmoodtablesController(AltunkayadbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
              return _context.Mahmoodtables != null ? 
                          View(await _context.Mahmoodtables.ToListAsync()) :
                          Problem("Entity set 'AltunkayadbContext.Mahmoodtables'  is null.");
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Mahmoodtables == null)
            {
                return NotFound();
            }

            var mahmoodtable = await _context.Mahmoodtables
                .FirstOrDefaultAsync(m => m.Id == id);
            if (mahmoodtable == null)
            {
                return NotFound();
            }

            return View(mahmoodtable);
        }
        public IActionResult Create()
        {
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UrunAdi,EklenmeTarihi,SontuketimTarihi")] Mahmoodtable mahmoodtable)
        {
            if (ModelState.IsValid)
            {
                _context.Add(mahmoodtable);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(mahmoodtable);
        }

     
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Mahmoodtables == null)
            {
                return NotFound();
            }

            var mahmoodtable = await _context.Mahmoodtables.FindAsync(id);
            if (mahmoodtable == null)
            {
                return NotFound();
            }
            return View(mahmoodtable);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UrunAdi,EklenmeTarihi,SontuketimTarihi")] Mahmoodtable mahmoodtable)
        {
            if (id != mahmoodtable.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(mahmoodtable);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MahmoodtableExists(mahmoodtable.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(mahmoodtable);
        }

        
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Mahmoodtables == null)
            {
                return NotFound();
            }

            var mahmoodtable = await _context.Mahmoodtables
                .FirstOrDefaultAsync(m => m.Id == id);
            if (mahmoodtable == null)
            {
                return NotFound();
            }

            return View(mahmoodtable);
        }

       
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Mahmoodtables == null)
            {
                return Problem("Entity set 'AltunkayadbContext.Mahmoodtables'  is null.");
            }
            var mahmoodtable = await _context.Mahmoodtables.FindAsync(id);
            if (mahmoodtable != null)
            {
                _context.Mahmoodtables.Remove(mahmoodtable);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MahmoodtableExists(int id)
        {
          return (_context.Mahmoodtables?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

AltunkayaBurada/AltunkayaBurada/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
    <script src="https://unpkg.com/scrollreveal"></script>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Altunkayashop</title>
    <link rel="stylesheet" href="~/css/bootSwatchTemplate.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AltunkayaBurada.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-light" data-bs-theme="dark">
            <div class="container-fluid">
                @*<a class="navbar-brand" href="#">AltunkayaShop</a>*@
                <a class="navbar-brand text-dark " asp-area="" asp-controller="Home" asp-action="Index">AltunkayaShop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor03">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">ANASAYFA</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Mahmoodtables" asp-action="Index">MAHMOOD</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Altunsatables" asp-action="Index">ALTUNSA</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Confytables" asp-action="Index">CONFY</a>
                        </li>
                    </ul>
                   @* <form class="d-flex">
                        <input class="form-control me-sm-2" type="search" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>*@
                </div>
            </div>
        </nav>
        @*<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 .headline">
            <div class="container-fluid .headline">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AltunkayaBurada</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between .headline">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">ANASAYFA</a>
                        </li>
                     
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Mahmoodtables" asp-action="Index">MAHMOOD</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Altunsatables" asp-action="Index">ALTUNSA</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Confytables" asp-action="Index">CONFY</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>*@
    </header>
    <div class="container .headline">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted .headline">
        <div class="container .headline">
            &copy; 2023 - AltunkayaBurada - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script>
        ScrollReveal().reveal('.headline',{ delay:1000 });
    </script>
</body>
</html>